name: 'Elasticsearch plugin github action'
description: 'GitHub actio that builds elasticsearch plugins'

runs:
  using: "composite"
  steps:
  - uses: actions/download-artifact@v4
    with:
      name: elasticsearch-plugin

  - name: Create release
    uses: ncipollo/release-action@v1
    with:
      artifacts: '*.zip,*.deb'
